language: cpp

compiler:
  - gcc
  - clang

os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

before_script:
- export CC=gcc-7
- export CXX=g++-7
- mkdir cmake-build-test
- cd cmake-build-test
- cmake ..

script:
  - make
  - test/unittest/EasyExceptionUnitTest
  - ./CustomException
  - ./JsonException
  - ./LoggerInheritance
  - ./SimpleException
  - ./SimpleStacktrace