language: cpp

matrix:
  include:
    # gcc-7
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
    # clang 5.0
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0

before_script:
- mkdir cmake-build-test
- cd cmake-build-test
- cmake ..

script:
  - make
  - test/unittest/EasyExceptionUnitTest
  - ./CustomException
  - ./JsonException
  - ./LoggerInheritance
  - ./SimpleException
  - ./SimpleStacktrace