language: cpp

matrix:
  include:

    # gcc-7
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # clang 5.0
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir cmake-build-test
  - cd cmake-build-test
  - cmake ..

script:
  - make
  - test/unittest/EasyExceptionUnitTest
  - ./CustomException
  - ./JsonException
  - ./LoggerInheritance
  - ./SimpleException
  - ./SimpleStacktrace